baseurl      = "/"
title        = "The Ithacan Transit Guide"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10
defaultTheme = "light"
themeColor = "#252627"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "the best all-in-one guide to navigating Ithaca"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  # enableGlobalLanguageMenu = true

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "The Ithacan Transit Guide"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

  [languages.en.params]
    subtitle  = "A simple theme for Hugo"

    [languages.en.params.logo]
      logoText = "The Ithacan Transit Guide"
      logoHomeLink = "/"
      #logoCursorColor = "
      logoCursorAnimate = "2s"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [menu]
    [[menu.main]]
        identifier = "Around Ithaca"
        name       = "Around Ithaca"
        url        = "/around_ith"
    [[menu.main]]
        identifier = "To/From Ithaca"
        name       = "To/From Ithaca"
        url        = "/to_from_ith"